INFO:root: 2021-03-04 17:27:41.111361: Bernard constructed
INFO:root: 2021-03-04 17:27:41.112103: Bernard initialized
INFO:root: 2021-03-04 17:33:26.931570: Bernard received command: "AT Juzang +698878.0092391968 kiwi.cs.ucla.edu +34.068930-118.445127 1614209128.918963997"
INFO:root: 2021-03-04 17:33:26.932231: Received "AT Juzang +698878.0092391968 kiwi.cs.ucla.edu +34.068930-118.445127 1614209128.918963997" from Juzang
INFO:root: 2021-03-04 17:33:26.933013: Bernard failed to connect to Jaquez
INFO:root: 2021-03-04 17:33:26.933709: Bernard failed to connect to Juzang
INFO:root: 2021-03-04 17:33:26.934576: Bernard failed to connect to Campbell
INFO:root: 2021-03-04 17:33:26.934703: Bernard replied with: "AT Juzang +698878.0092391968 kiwi.cs.ucla.edu +34.068930-118.445127 1614209128.918963997"
INFO:root: 2021-03-04 17:33:26.934816: Client disconnected
INFO:root: 2021-03-04 17:33:58.011320: Bernard received command: "AT Juzang +698909.0889830589 kiwi.cs.ucla.edu +34.068930-118.445127 1614209128.918963997"
INFO:root: 2021-03-04 17:33:58.012299: Propagation from Juzang already received
INFO:root: 2021-03-04 17:33:58.012418: Bernard replied with: "None"
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-10' coro=<Server.get_commands() done, defined at server.py:53> exception=TypeError("unsupported operand type(s) for +: 'NoneType' and 'str'")>
Traceback (most recent call last):
  File "server.py", line 81, in get_commands
    reply = reply + "\n"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
INFO:root: 2021-03-04 17:38:03.281879: Bernard received command: ""
INFO:root: 2021-03-04 17:38:03.282030: Client disconnected
INFO:root: 2021-03-04 17:38:04.558165: Bernard received command: ""
INFO:root: 2021-03-04 17:38:04.558323: Client disconnected
INFO:root: 2021-03-04 17:38:06.893712: Bernard failed to start
